config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :posts do
    resources :comments do
      member do
        post "approve"
      end
    end
  end
  
  resources :projects do 
    resources :comments do
      member do
        post "approve"
      end
    end
  end 

  scope ":locale" do
  end 

  root 'static_pages#index'

  get '/ploppycat' => 'static_pages#ploppy_cat'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post

end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :author, class_name: "User"
	has_many :comments, as: :commentable

def publish!
  self.published = true
  save!
end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    if user_signed_in?
      if current_user.editor?
        @posts = Post.all.decorate
      else
        @posts = Post.where("author_id = ? or published = ?", current_user.id, true).decorate
      end
    else
      @posts = Post.where(published: true).decorate
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = @post.comments.new
    @comments = policy_scope(Comment).where(commentable: @post)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    current_user.posts << @post

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, (:published if current_user.role == "editor"))
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.input :title %>
  <%= f.input :body %>
  <%= f.button :submit %>
  <% if policy(@post).publish? %>
    <div class="row collapse">
    <div class="small-3 columns">
      <%= f.label :published, class: "right inline", title: "Is this post published?", data: {tooltip: true } %><br>
    </div>
    <div class="small-9 columns">
      <%= f.check_box :published %>
    </div>
  </div>
  <% end %>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <span class="timestamp">at <%= l post.created_at %></span>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.intro %></td>
        <td><%= link_to 'Show', post %></td>
        <td>
          <% if policy(post).update? %>
          <%= link_to 'Edit', edit_post_path(post) %>
          <% end %>
        </td>
        <td>
          <% if policy(post).delete? %>
          <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if policy(Post).create? %>
  <%= link_to 'New Post', new_post_path, class: "button radius"%>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p id="author">
	<b>By:</b>
	<%= @post.author.email %>
</p>

<p id="status">
	<b>Status:</b>
	<%= @post.published? ? "Published" : "Unpublished" %>
</p>

<h3>Comments:</h3>
<% @comments.each do |c| %>
<p> <%= c.content %>
	<% unless c.approved? %>
	<%= link_to "Approve", approve_post_comment_path(@post, c), method: :post %>
	<% end %>

</p>
<% end %>
<%= render "comments/form", commentable: @post %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>