config/routes.rb
Portfolio::Application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}
  resources :posts do
    resources :comments do
      member do
        post "approve"
      end
    end
  end
  
  resources :projects do 
    resources :comments do
      member do
        post "approve"
      end
    end
  end 

  scope ":locale" do
  end 

  root 'static_pages#index'

  get '/ploppycat' => 'static_pages#ploppy_cat'

  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create', :via => :post

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Joslyn Rosbrook" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class ="top-bar">
      <ul class="title-area">
        <li class="name">
          <h1 id="nav-name"><%= link_to "Joslyn Rosbrook", root_path %></h1>
        </li>
      </ul>
     <section class="top-bar-section">
        <ul class="right">
          <li class="divider"></li>
          <li><%= link_to "About", "#" %></li>
          <li class="divider"></li>
          <li><%= link_to "Blog", posts_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Projects", projects_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Contact Me", contact_path %></li>
          <li class="divider"></li>
          <% if user_signed_in? %>
            <li>
            <%= link_to 'Log Out', destroy_user_session_path, :method => :delete %>
            </li>
          <% else %>
            <li>
            <%= link_to 'Sign Up', new_user_registration_path %>
            </li>
            <li>
            <%= link_to 'Log In', new_user_session_path %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <div id="user_nav">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.email %></strong>.
      <% end %>
    </div>

    <% flash.each do |key, value| %>
        <div class="alert-box <%= flash_class(key) %>">
              <%= value %>
        </div>
    <% end %>


    <div class="columns large-8">
    	<%= yield %>
    </div>



  </body>
</html>